import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpageone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpageseven" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageSeven
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpagefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpagefive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpagetwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpagethree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/landingpagesix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            LandingPageSix
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
